site_name: rrmesh
site_url: https://rrmesh.net/
#repo_url: https://github.com/RockRiverMesh/rrmesh.net
#repo_name: RRMesh/rrmesh.net
edit_uri: "https://github.com/RockRiverMesh/rrmesh.net/edit/main/docs"
copyright: 'Copyright &copy; 2025 Rock River Mesh <u><a href="https://github.com/RockRiverMesh/rrmesh.net">Contributors</a></u><br><p style="margin:0">Rock River Mesh is not affilated with <u><a href="https://meshtastic.org" target="_blank" rel="noreferrer noopener">Meshtastic®</a></u>, nor endorsed by <u><a href="https://meshtastic.org/docs/legal/licensing-and-trademark" target="_blank" rel="noreferrer noopener">Meshtastic LLC</a></u>.</p>'

nav:
  - Home: 'index.md'
  - Meshtastic:
    - 'meshtastic/index.md'
    - Guides: 'meshtastic/guides/index.md'
    - Map: 'meshtastic/map.md'
    - MQTT: 'meshtastic/mqtt/index.md'
  - Resources: 'resources/index.md'
  - Contact: 'contact.md'

theme:
  name: material
  custom_dir: overrides
  logo: assets/rrmesh_logo.svg
  favicon: assets/rrmesh_favicon.png
  font:
    text: montserrat
  features:
    - content.action.edit
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    primary: blue
    accent: light green

markdown_extensions: 
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - git-revision-date-localized:
  - drawio:
      edit: false
      darkmode: true
  - glightbox
  - offline
  - privacy
  - tags

validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn

extra_javascript:
  - https://viewer.diagrams.net/js/viewer-static.min.js
  - assets/javascripts/drawio-reload.js
